# docker-compose.infra.prod.yml

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: postgresdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fgmi_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d fgmi_db || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks: [node-network]

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks: [node-network]

volumes:
  dbdata:
