version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - node-network

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - node-network

  myip:
    image: jason5ng32/myip
    container_name: myip-checker
    restart: always
    ports:
      - '8080:8080'
    networks:
      - node-network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/www/node-app/fgmibe_repository/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
