version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '4000:4000'
    depends_on:
      - postgresdb
      - redis
      - myip
      - nginx
      - certbot
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - node-network

  myip:
    image: jason5ng32/myip
    container_name: myip-checker
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - node-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - node-app
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
